# Midterm 2 Template

In [1]:
import numpy as np
import sympy
from sympy import *
from sympy.physics.vector.printing import vlatex
from IPython.display import Math, display

init_printing()

def dotprint(expr):
    display(Math(vlatex(expr)))

# 6.

In [2]:
A = np.vstack([[1,2,-4,-8], [1,0,0,0], [0,1,0,0],[0,0,1,0]])
B = np.hstack([1,0,0,0])
C = np.hstack([0,0,-1,2])

In [3]:
# im dumb and figured it out mentally

# 8.

In [4]:
C8 = np.vstack([[1, 2, -1], [1, 2, -1], [-1, -2, 1]])
det_C8 = np.linalg.det(C8)
det_C8

# 9.

In [5]:
A9 = np.vstack([[1, 2], [0, 1]])
B9 = np.hstack([1,-1])
C9 = np.array([0, 3])

alpha9 = np.array([-4, 13])

In [6]:
contr9 = np.array([B9, A9@B9])
contr9

array([[ 1, -1],
       [-1, -1]])

In [7]:
np.poly(A9)

array([ 1., -2.,  1.])

In [8]:
AA = np.array([[1, -2], [0, 1]])
AA

array([[ 1, -2],
       [ 0,  1]])

AA top right is the coeff of my s^1 term, which is -2

# 12 - 15

In [34]:
A12 = np.vstack([[-1, 4], [1, 0]])
B12 = np.array([[1],[0]])
C12 = np.array([1, -1])


contr12 = np.array([B12, A12@B12])
alpha12 = np.array([-2, 5])
B12

array([[1],
       [0]])

In [10]:
np.poly(A12)

array([ 1.,  1., -4.])

i can't find the right aA value and that's messing EVERYTHING up

i don't know what to do. i'm mad.

there's just a stupid note that says "a_A = coeff of bottom row of A" but that clearly isn't the right thing 

i'm trying the second and third coefficients from poly(A10), maybe that will work

In [11]:
np.poly(A12)

array([ 1.,  1., -4.])

In [12]:
aA = np.array([1, -4])

the issue now is my AA isn't matching anything and my resulting K matrix doesn't match...

alpha is my closed loop coeeficients

aA is my open loop coeffs, right?????? why doesn't this work

In [13]:
AA = np.vstack([[1, -1], 
                [0, 1]])

In [14]:
np.linalg.matrix_rank(contr12)

np.int64(2)

In [15]:
K = (alpha12 - aA) @ np.linalg.inv(AA) @ np.linalg.inv(contr12)
K

array([3., 6.])

In [44]:
K13 = np.array([2,6])
A13 = np.vstack([[-1, 4], [1, 0]])
B13 = np.array([[1],[0]])
# poles13 = A12 - B13@K13
# np.linalg.eigvals(poles13)
K13.shape

In [ ]:
B = np.array([[2,1]])

<IPython.core.display.Math object>

"the poles are the eigvals of A-BK" is on my notes sheet, but these don't match. i guess it's a none of the above?????????


# 14.

# 15.

In [17]:
O = np.vstack([C10, C10 @ A10])
O

NameError: name 'C10' is not defined